// tf2hub-vite/src/pages/Home.tsx
import { useEffect, useState } from "react";
import { Tag } from "@models/Tag";
import "./Home.scss";
import { DataService } from "@services/data-service";
import { Data } from "@models/Data";
import CardDisplay from "./CardDisplay";

export interface TagFilter {
  text: string;
  value: Tag;
}

function Home() {
  const tags = [
    { text: "All" } as TagFilter,
    { text: "Featured", value: Tag.Featured } as TagFilter,
    {
      text: "Official Sites",
      value: Tag.Official,
    } as TagFilter,
    {
      text: "Community Servers",
      value: Tag.CommunityServers,
    } as TagFilter,
    {
      text: "Communities",
      value: Tag.Communities,
    } as TagFilter,
    { text: "Events", value: Tag.Events } as TagFilter,
    {
      text: "Enhancements",
      value: Tag.Enhancements,
    } as TagFilter,
    { text: "Tools", value: Tag.Tools } as TagFilter,
    { text: "Mods", value: Tag.Mods } as TagFilter,
    {
      text: "Competitive",
      value: Tag.Competitive,
    } as TagFilter,
    { text: "Trading", value: Tag.Trading } as TagFilter,
    {
      text: "Marketplaces",
      value: Tag.Marketplaces,
    } as TagFilter,
  ];

  const [selectedTag, setSelectedTag] = useState(tags[0]);
  const [searchText, setSearchText] = useState("");

  const [data, setData] = useState<Data[]>([]);

  useEffect(() => {
    const dataService = new DataService();
    const data = dataService.getData({
      tag: selectedTag.value,
      search: searchText,
    });
    setData(data);
  }, [searchText, selectedTag]);

  return (
    <div className="home">
      <div className="welcome">
        <div className="title">Welcome!</div>
        <div
          className="text"
          style={{ display: "flex", flexDirection: "column", gap: "1rem" }}
        >
          <div>
            Here you can find all of the most popular TF2-related sites,
            including official sites, trading sites, community projects, and
            more.
          </div>
          <div>
            This site was created with the intent of helping newcomers to TF2
            find helpful resources all in one place.
          </div>
          <div>
            TF2 Hub is still in development, but if you find a problem or would
            like to request a feature, please visit our{" "}
            <a href="https://github.com/theaswanson/tf2hub" target="_blank">
              GitHub repo
            </a>
            .
          </div>
        </div>
      </div>
      <div className="filters" style={{ display: "flex", gap: "0 1rem" }}>
        {tags.map((tag, i) => (
          <div className="card" key={i} onClick={() => setSelectedTag(tag)}>
            <div
              className={`card-content filter ${
                tag.text === selectedTag.text ? "selected" : ""
              }`}
            >
              <div className="header">
                <div className="title">
                  <span>{tag.text}</span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div className="search">
        <div className="card">
          <div className="card-content">
            <input
              type="text"
              placeholder="Search..."
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
            />
          </div>
        </div>
      </div>
      <CardDisplay data={data} />
    </div>
  );
}

export default Home;

// tf2hub/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../data.service';
import { Data } from '../models/Data';
import { Filter } from '../models/Filter';
import { Tag } from '../models/Tag';

export class TagFilter {
  text: string;
  value: Tag;
  selected: boolean;
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  tags: TagFilter[];
  data: Data[];
  selectedTag: TagFilter;
  searchText: string;

  constructor(private dataService: DataService) {
    this.tags = [
      { text: 'All', selected: true } as TagFilter,
      { text: 'Featured', value: Tag.Featured, selected: false } as TagFilter,
      { text: 'Official Sites', value: Tag.Official, selected: false } as TagFilter,
      { text: 'Community Servers', value: Tag.CommunityServers, selected: false } as TagFilter,
      { text: 'Communities', value: Tag.Communities, selected: false } as TagFilter,
      { text: 'Events', value: Tag.Events, selected: false } as TagFilter,
      { text: 'Enhancements', value: Tag.Enhancements, selected: false } as TagFilter,
      { text: 'Tools', value: Tag.Tools, selected: false } as TagFilter,
      { text: 'Mods', value: Tag.Mods, selected: false } as TagFilter,
      { text: 'Competitive', value: Tag.Competitive, selected: false } as TagFilter,
      { text: 'Trading', value: Tag.Trading, selected: false } as TagFilter,
      { text: 'Marketplaces', value: Tag.Marketplaces, selected: false } as TagFilter,
    ];
    this.selectedTag = this.tags[0];
    this.searchText = "";
  }

  ngOnInit(): void {
    this.getData();
  }

  selectTag(selectedTag: TagFilter): void {
    for (const tag of this.tags) {
      tag.selected = false;
    }
    selectedTag.selected = true;
    this.selectedTag = selectedTag;
    this.getData();
  }

  getData(): void {
    this.data = this.dataService.getData({
      tag: this.selectedTag.value,
      search: this.searchText
    } as Filter);
  }

  searchChanged(value: any): void {
    this.searchText = value;
    this.getData();
  }

}

<div fxLayout="row" fxLayout.lt-lg="column" fxLayoutGap="2rem">
  <div fxFlex="50">
    <div class="card" routerLink="/official-sites">
      <div class="card-content">
        <div class="header">
          <div class="title">Official Sites</div>
        </div>
      </div>
    </div>
  </div>
  <div fxFlex="50">
    <div class="card" routerLink="/projects">
      <div class="card-content">
        <div class="header">
          <div class="title">Projects</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div fxLayout="row" fxLayout.lt-lg="column" fxLayoutGap="2rem">
  <div fxFlex="50">
    <div class="card" routerLink="/communities">
      <div class="card-content">
        <div class="header">
          <div class="title">Communities</div>
        </div>
      </div>
    </div>
  </div>
  <div fxFlex="50">
    <div class="card" routerLink="/trading">
      <div class="card-content">
        <div class="header">
          <div class="title">Trading</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div fxLayout="row" fxLayout.lt-lg="column" fxLayoutGap="2rem">
  <div fxFlex="50">
    <div class="card" routerLink="/marketplaces">
      <div class="card-content">
        <div class="header">
          <div class="title">Marketplaces</div>
        </div>
      </div>
    </div>
  </div>
  <div fxFlex="50">
    <div class="card" routerLink="/competitive">
      <div class="card-content">
        <div class="header">
          <div class="title">Competitive</div>
        </div>
      </div>
    </div>
  </div>
</div>

<h1>Welcome!</h1>
<p>Here you can find all of the most popular TF2-related sites, including official sites,
  trading sites, community projects, and more.</p>
<p>This site was created with the intent of helping newcomers to TF2 find helpful resources all in one place.</p>
<p>
  TF2Hub is still in development, but if you find a problem or would like to request a feature, please visit our
  <a href="https://github.com/theaswanson/tf2hub" target="_blank">GitHub repo</a>.
</p>
