// tf2hub-vite/src/CardDisplay.tsx
import { Data } from "./models/Data";
import "./CardDisplay.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  IconDefinition,
  faBook,
  faEarthAmericas,
  faEarthAsia,
  faEarthEurope,
  faGlobe,
} from "@fortawesome/free-solid-svg-icons";
import {
  faDiscord,
  faFacebook,
  faGithub,
  faInstagram,
  faRedditAlien,
  faSteam,
  faTwitch,
  faXTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

function CardDisplay({ data }: { data: Data[] }) {
  const getIcon = (linkText: string): IconDefinition => {
    switch (linkText) {
      case "Website":
        return faGlobe;
      case "Docs":
        return faBook;
      case "Twitter":
        return faXTwitter;
      case "Twitch":
        return faTwitch;
      case "Reddit":
        return faRedditAlien;
      case "YouTube":
        return faYoutube;
      case "Discord":
        return faDiscord;
      case "GitHub":
        return faGithub;
      case "Steam Group":
        return faSteam;
      case "Facebook":
        return faFacebook;
      case "Instagram":
        return faInstagram;
      case "NA Website":
        return faEarthAmericas;
      case "EU Website":
        return faEarthEurope;
      case "SEA Website":
        return faEarthAsia;
      default:
        return faGlobe;
    }
  };

  return (
    <div className="grid-container">
      {data.map((item, i) => (
        <div className="grid-item" key={i}>
          <div className="card">
            <div className="card-content">
              <div className="header">
                <div className="top">
                  <div className="title">{item.title}</div>
                  <div className="subtitle">{item.subtitle}</div>
                </div>
                {item.url && <div className="subtitle">{item.url}</div>}
              </div>
              <div
                className="text"
                style={{
                  display: "flex",
                  flexDirection: "column",
                  gap: "1rem",
                }}
              >
                {item.description.map((descriptionLine) => descriptionLine)}
              </div>
              <div className="links">
                {item.links.map((link, i) => (
                  <a href={link.href} target="_blank" key={i}>
                    <FontAwesomeIcon icon={getIcon(link.text)} size="lg" />
                  </a>
                ))}
              </div>
              {item.img && (
                <div className="image">
                  <a href={item.links[0].href} target="_blank">
                    <img src={item.img.src} alt={item.title} />
                  </a>
                </div>
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

export default CardDisplay;

// tf2hub/src/app/card-display/card-display.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { faDiscord, faFacebook, faGithub, faInstagram, faReddit, faSteam, faTwitch, faTwitter, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { IconDefinition } from '@fortawesome/free-regular-svg-icons';
import { faBook, faGlobe, faGlobeAmericas, faGlobeAsia, faGlobeEurope } from '@fortawesome/free-solid-svg-icons';
import { Data } from '../models/Data';

@Component({
  selector: 'app-card-display',
  templateUrl: './card-display.component.html',
  styleUrls: ['./card-display.component.scss']
})
export class CardDisplayComponent implements OnInit {

  faGlobe = faGlobe;
  faGlobeAmericas = faGlobeAmericas;
  faGlobeEurope = faGlobeEurope;
  faGlobeAsia = faGlobeAsia;
  faYouTube = faYoutube;
  faDiscord = faDiscord;
  faTwitch = faTwitch;
  faTwitter = faTwitter;
  faGithub = faGithub;
  faSteam = faSteam;
  faFacebook = faFacebook;
  faInstagram = faInstagram;
  faBook = faBook;
  faReddit = faReddit;

  theData: Data[];
  get data(): Data[] {
    return this.theData;
  }
  @Input() set data(value: Data[]) {
    this.theData = value;
  }

  constructor() { }

  ngOnInit(): void {
  }

  getIcon(linkText: string): IconDefinition {
    switch (linkText) {
      case 'Website':
        return this.faGlobe;
      case 'Docs':
        return this.faBook;
      case 'Twitter':
        return this.faTwitter;
      case 'Twitch':
        return this.faTwitch;
      case 'Reddit':
        return this.faReddit;
      case 'YouTube':
        return this.faYouTube;
      case 'Discord':
        return this.faDiscord;
      case 'GitHub':
        return this.faGithub;
      case 'Steam Group':
        return this.faSteam;
      case 'Facebook':
        return this.faFacebook;
      case 'Instagram':
        return this.faInstagram;
      case 'NA Website':
        return this.faGlobeAmericas;
      case 'EU Website':
        return this.faGlobeEurope;
      case 'SEA Website':
        return this.faGlobeAsia;
      default:
        return this.faGlobe;
    }
  }
}

<div fxLayout="row" fxLayout.lt-lg="column" fxLayoutGap="2rem"
  *ngFor="let item of [].constructor(numberOfRows); let rowIndex = index">
  <div [fxFlex]="columnWidth"
    *ngFor="let item2 of [].constructor(getNumberOfItemsInRow(rowIndex)); let columnIndex = index">
    <div class="card">
      <div class="card-content">
        <div class="header">
          <div class="title">{{data[getItemIndex(rowIndex, columnIndex)].title}}</div>
          <div class="subtitle">{{data[getItemIndex(rowIndex, columnIndex)].subtitle}}</div>
        </div>
        <div class="text" fxLayout="column" fxLayoutGap="1rem">
          <div *ngFor="let desc of data[getItemIndex(rowIndex, columnIndex)].description">
            {{desc}}
          </div>
        </div>
        <div class="links">
          <a mat-button [href]="link.href" target="_blank"
            *ngFor="let link of data[getItemIndex(rowIndex, columnIndex)].links">{{link.text}}</a>
        </div>
        <div class="image">
          <img [src]="data[getItemIndex(rowIndex, columnIndex)].img.src"
            [alt]="data[getItemIndex(rowIndex, columnIndex)].title"
            *ngIf="data[getItemIndex(rowIndex, columnIndex)].img" />
        </div>
      </div>
    </div>
  </div>
</div>
