// tf2hub-vite/src/pages/Trashcan.tsx
import { useState } from "react";
import "./Trashcan.scss";
import { TrashcanService } from "@services/trashcan-service";

function Trashcan() {
  const [bindsText, setBindsText] = useState("");
  const [bindKey, setBindKey] = useState("");

  const buildConfig = () => {
    if (!bindsText || bindsText.length === 0) {
      alert("Enter at least one bind before generating.");
      return;
    }

    if (!bindKey) {
      alert("Enter a bind key before generating.");
      return;
    }

    const configFileText = new TrashcanService().build(
      bindsText.split("\n"),
      bindKey
    );

    downloadBlob(
      new Blob([configFileText], { type: "text/plain" }),
      "trashcan.cfg"
    );
  };

  const downloadBlob = (blob: Blob, fileName: string): void => {
    const a = document.createElement("a");
    a.setAttribute("style", "display:none;");
    document.body.appendChild(a);
    a.download = fileName;
    a.href = URL.createObjectURL(blob);
    a.target = "_blank";
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="trashcan">
      <div className="welcome">
        <div className="title">Trashcan Script Generator</div>
        <div
          className="text"
          style={{ display: "flex", flexDirection: "column", gap: "1rem" }}
        >
          <div>
            Use one key to cycle through binds. Simply enter each bind message
            on a new line, set your bind key, and hit generate.
          </div>
        </div>
      </div>

      <div className="settings">
        <div className="card">
          <div className="card-content">
            <textarea
              placeholder="Enter binds here, one per line..."
              rows={10}
              value={bindsText}
              onChange={(e) => setBindsText(e.target.value)}
            ></textarea>
            <input
              type="text"
              maxLength={1}
              placeholder="Bind key"
              value={bindKey}
              onChange={(e) => setBindKey(e.target.value)}
            />
          </div>
        </div>
      </div>

      <button color="primary" onClick={() => buildConfig()}>
        Generate
      </button>
    </div>
  );
}

export default Trashcan;

// tf2hub/src/app/trashcan/trashcan.component.ts
import { Component, OnInit } from '@angular/core';
import { TrashcanService } from '../trashcan.service';

@Component({
  selector: 'app-trashcan',
  templateUrl: './trashcan.component.html',
  styleUrls: ['./trashcan.component.scss']
})
export class TrashcanComponent implements OnInit {

  bindsText: string;
  bindKey: string;

  constructor(private trashcanService: TrashcanService) { }

  ngOnInit(): void {
  }

  buildConfig() {
    if (!this.bindsText) {
      alert('Enter at least one bind before generating.');
      return;
    }

    if (!this.bindKey) {
      alert('Enter a bind key before generating.');
      return;
    }

    let configFileText = this.trashcanService.build(this.bindsText.split('\n'), this.bindKey);
    this.downloadBlob(new Blob([configFileText], { type: 'text/plain' }), 'trashcan.cfg');
  }
  

  private downloadBlob(blob: Blob, fileName: string): void {
    const a = document.createElement('a');
    a.setAttribute('style', 'display:none;');
    document.body.appendChild(a);
    a.download = fileName;
    a.href = URL.createObjectURL(blob);
    a.target = '_blank';
    a.click();
    document.body.removeChild(a);
  }

}

<div class="welcome">
  <div class="title">Trashcan Script Generator</div>
  <div class="text" fxLayout="column" fxLayoutGap="1rem">
    <div>Use one key to cycle through binds. Simply enter each bind message on a new line, set your bind key, and hit generate.</div>
  </div>
</div>

<div class="settings">
  <div class="card">
    <div class="card-content">
      <textarea placeholder="Enter binds here, one per line..." rows="10" [(ngModel)]="bindsText"></textarea>
      <input type="text" maxlength="1" placeholder="Bind key" [(ngModel)]="bindKey" />
    </div>
  </div>
</div>

<button mat-button color="primary" (click)="buildConfig()">Generate</button>
